'use strict';
const d=window.REPLAY;
const chapters=[['overview','Overview'],['signal','The source note'],['memory','Proposed links'],['investigate','Two facilities'],['protect','Recorded protection'],['reuse','A reusable method'],['security','Security checks']];
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=(text,tone='green')=>`<span class="badge ${tone}">${esc(text)}</span>`;
const receipt=(label,value)=>`<div class="receipt"><span>${esc(label)}</span><code>${esc(value)}</code></div>`;
const details=(label,value)=>`<details><summary>${esc(label)}</summary><pre>${esc(JSON.stringify(value,null,2))}</pre></details>`;
const panel=(title,body,tag='')=>`<section class="panel"><div class="panel-head"><h3>${title}</h3>${tag}</div>${body}</section>`;
const heading=(chapter,title,subtitle,tag='')=>`<div class="eyebrow">${chapter}</div><div class="title-row"><div><h1>${title}</h1><p class="lede">${subtitle}</p></div>${tag}</div>`;
const insight=(title,text)=>`<div class="insight"><strong>${title}</strong>${text}</div>`;
const event=(label,title,text)=>`<div class="event"><div class="time">${label}</div><b>${title}</b><p>${text}</p></div>`;
const stat=(value,label,unit='')=>`<div class="stat"><span class="value">${esc(value)}</span><span class="unit">${unit}</span><div class="label">${label}</div></div>`;
const sponsorFlow=()=>`<div class="flow">${[['C','Cognee','Extract proposals'],['H','HydraDB','Keep provenance'],['ϟ','Hotdata','Query facility data'],['↗','RocketRide','Decide in Cloud'],['∞','Rote','Replay the method']].map(([mark,name,role])=>`<div class="sponsor"><span class="sponsor-mark">${mark}</span><b>${name}</b><small>${role}</small></div>`).join('')}</div>`;
const shortQty=q=>String(q).replace(/(\.\d*?)0+$/,'$1').replace(/\.$/,'');
function overview(){
 return `<div class="hero"><div class="hero-label">RECALL FIREWALL · EVIDENCE TO ACTION</div><h1>One uncertain note.<br>Two plants. A traceable response.</h1><p class="lede">Follow the evidence from a proposed material transfer to scoped facility checks and a verified protective hold.</p><div style="margin-top:20px">${badge('Five sponsor layers executed')} &nbsp; ${badge('Exposure remains unresolved','amber')}</div></div>
 <div class="stats">${stat(d.claims.length,'Source-linked proposals')}${stat(d.cloud.queried_facilities.length,'Facilities queried')}${stat('1','Protective hold verified')}${stat(d.replays.length,'Fresh method replays')}</div>
 <div class="grid">${panel('A connected investigation',`<p class="section-sub">The sponsors have distinct jobs. A source quote does not become a completed event, and a model answer does not become an analytical receipt.</p>${sponsorFlow()}${insight('The question that changes the investigation','Did the retained blend actually move into another batch? The note suggests it. Completion records are still needed.')}`)}${panel('The recorded path',`<div class="timeline">${event('01 · SOURCE','A planning note introduces a possible link','Cognee extracts three proposals from the original text.')}${event('02 · INVESTIGATE','The link changes what gets queried','RocketRide checks PLANT-A, then dispatches PLANT-B.')}${event('03 · PROTECT','A simulated hold is read back','A departure attempt returns 409: blocked.')}${event('04 · REUSE','The procedure runs on different inputs','Rote returns fresh query IDs and matching receipts.')}</div>`)}</div>`;
}
function signal(){
 return heading('01 / THE SOURCE NOTE · COGNEE','A clue is not a completed event.','The investigation starts with a fictional planning note. Cognee extracts proposed relationships; the original words remain attached.',badge('3 proposals extracted'))+
 `<div class="grid">${panel('Planning note',`<div class="document"><blockquote>${esc(d.source.text)}</blockquote><div class="document-footer">${esc(d.source.source_id)} &nbsp; · &nbsp; Version ${esc(d.source.source_version)} &nbsp; · &nbsp; PLANT-A</div></div>${insight('“May” matters.','Every link stays PROPOSED. The note alone does not prove that a transfer, consumption, or repack occurred.')}`)}${panel('What Cognee contributed',d.claims.map(c=>`<div class="claim"><div class="claim-id">${esc(c.input_lot)} → ${esc(c.output_lot)}</div><p>${esc(c.quote)}</p></div>`).join('')+receipt('Cognee ingestion run',d.cognee_run)+details('Inspect the source pointer',d.claims.find(c=>c.input_lot==='INT-1000').source))}</div>`;
}
function memory(){
 const nodes=['INT-1000','INT-2000','INT-2002','CASE-DEMO'];
 return heading('02 / PROPOSED LINKS · HYDRADB','Keep the link. Keep its source.','HydraDB stores the source-linked proposals. A separate process retrieves them with the original provenance intact.',badge('Read-back verified'))+
 panel('Candidate material path',`<div class="lineage">${nodes.map((n,i)=>`${i?'<div class="edge"><span>proposed</span></div>':''}<div class="lot"><small>${i===0?'RETAINED LOT':i===3?'POSSIBLE REPACK':'POSSIBLE OUTPUT'}</small><b>${n}</b></div>`).join('')}</div><p class="section-sub">Dashed links are hypotheses to investigate. They are not supported exposure paths.</p>`)+
 `<div class="grid" style="margin-top:23px">${panel('Provenance travels with the claim',`<div class="row"><span class="muted">Source-linked claims</span><b>${d.claims.length}</b></div><div class="row"><span class="muted">Reader-process pages</span><b>${d.hydra_pages}</b></div><div class="row"><span class="muted">Published manifest</span>${badge('Matched on retrieval')}</div><div class="row"><span class="muted">Event support</span>${badge('Still proposed','amber')}</div>${receipt('HydraDB native request',d.hydra_receipt)}`)}${panel('What this unlocks',`<h2>Another facility becomes<br>a question worth asking.</h2><p class="section-sub">INT-1000 appears in PLANT-A’s records. Its proposed link to INT-2000 gives the Cloud procedure a reason to inspect PLANT-B.</p>${insight('Durable memory, with boundaries','The retrieved claim points back to the source. It does not erase uncertainty or authorize a warehouse action.')}${details('Inspect all three claims',d.claims)}`)}</div>`;
}
function facility(f){return panel(esc(f.facility_id),`<div class="plant-heading"><small>Ingredient ING-041 · Gateway-bound database</small>${badge(f.rows.length+' records')}</div><table class="record-table"><thead><tr><th>Work order</th><th>Output lot</th><th>Recorded input</th></tr></thead><tbody>${f.rows.map(r=>`<tr><td class="mono">${esc(r.work_order_id)}</td><td class="mono">${esc(r.output_lot)}</td><td>${esc(shortQty(r.qty_kg))} kg</td></tr>`).join('')}</tbody></table><p class="section-sub">Recorded ingredient consumption by output lot. These rows are not an exposure total or a complete mass balance.</p>${receipt('Hotdata native query',f.query_run_id)}${details('Inspect query + gateway receipt',f)}`);}
function investigate(){
 return heading('03 / TWO FACILITIES · ROCKETRIDE + HOTDATA','The evidence decides the next query.','A reviewed procedure runs inside RocketRide Cloud. The gateway binds each task’s database; Hotdata returns records with native query IDs.',badge('Both branches verified'))+
 panel('Decision recorded in RocketRide Cloud',`<div class="branch"><div class="step"><strong>Read PLANT-A</strong>Fresh, scoped Hotdata records</div><span class="arrow">→</span><div class="step"><strong>Match a proposed link</strong>INT-1000 appears in the results</div><span class="arrow">→</span><div class="step"><strong>Query PLANT-B</strong>Read back both receipts</div></div><div class="callout"><strong>Next step: request completion records</strong>The proposed transfer remains unresolved. Both facilities were queried; neither query establishes that the transfer happened.</div>`)+
 `<div class="grid" style="margin-top:23px;grid-template-columns:1fr 1fr">${d.cloud.findings.map(facility).join('')}</div>`+
 insight('The counterexample took a different branch.','For ING-999, PLANT-A returned no rows. RocketRide requested source coverage and did not query PLANT-B. Empty is not the same as safe.');
}
function protect(){const h=d.hold;return heading('04 / RECORDED PROTECTION · LOCAL SIMULATOR','A hold is a state change, not a sentence.','A separately approved simulator command was executed, independently read back, and challenged with a departure attempt.',badge('Protective hold verified'))+
 `<div class="grid">${panel('SHIP-DEMO-A',`<div class="hold-main"><div class="shield">✓</div><div><div class="big">${esc(shortQty(h.read_back.qty_kg))}<span>kg</span></div><p>INT-1000 · PLANT-A · simulated shipment quantity</p></div></div><div class="row"><span class="muted">Transport state</span><b>STAGED</b></div><div class="row"><span class="muted">Protective state</span>${badge('HELD')}</div><div class="row"><span class="muted">Resulting version</span><b>${h.read_back.version}</b></div>${receipt('Approval bound to this hold',h.hold.approval_id)}${details('Inspect the recorded hold and read-back',h)}`)}${panel('Verify the effect',`<div class="check-row"><span class="check-mark">✓</span><div><b>Approval checked</b><small>The command carries an approval ID and plan hash.</small></div></div><div class="check-row"><span class="check-mark">✓</span><div><b>Hold read back</b><small>A separate read returns held = 1, version 2.</small></div></div><div class="check-row"><span class="check-mark">✓</span><div><b>Departure blocked</b><small>HTTP 409 · DEPARTURE_BLOCKED</small></div></div>${insight('A verified hold is not global containment.','This fictional shipment is protected in the simulator. The proposed material links and broader incident coverage remain open.')}`)}</div>`;}
function reuse(){return heading('05 / A REUSABLE METHOD · ROTE','Reuse the method. Query the facts again.','A real query and its dependent receipt read-back were captured in Rote, then parameterized for different facility and ingredient inputs.',badge('3 fresh replays verified'))+
 panel('Recorded procedure',`<div class="branch"><div class="step"><strong>1. Read consumption</strong>Facility + ingredient parameters</div><span class="arrow">→</span><div class="step"><strong>2. Read that receipt</strong>Use the new receipt ID from step 1</div><span class="arrow">→</span><div class="step"><strong>3. Compare provenance</strong>Query ID + result hash + current status</div></div>`)+
 `<div class="panel"><div class="panel-head"><h3>Different inputs. Fresh evidence.</h3>${badge('No prior affected-lot list reused','gray')}</div><table class="record-table"><thead><tr><th>Facility</th><th>Ingredient</th><th>Rows returned</th><th>Receipt read-back</th></tr></thead><tbody>${d.replays.map(r=>`<tr><td>${esc(r.finding.facility_id)}</td><td class="mono">${esc(r.finding.arguments.ingredient_id)}</td><td>${r.finding.rows.length}</td><td>${badge(r.receipt_verified?'Verified':'Unverified')}</td></tr>`).join('')}</tbody></table><p class="section-sub">Each replay issued a new Hotdata query. Vendor fixture databases were reused; these runs do not establish fresh-snapshot acceptance or a speedup.</p>${details('Inspect the three Rote run IDs and receipts',d.replays.map(r=>({run_id:r.run_id,query_run_id:r.finding.query_run_id,receipt_id:r.finding.receipt_id,coverage:r.finding.coverage})))}</div>`+
 insight('The zero-row case is part of the proof.','PLANT-B / ING-999 returned no records, with coverage still marked incomplete. The method preserved the gap instead of producing a false-safe answer.');}
function security(){const s=d.security;return heading('06 / SECURITY CHECKS · SNYK','Security results you can inspect.','Recorded scan results, with a clear distinction between dependency scanning and source-code analysis.',badge('Dependency scans clean'))+
 `<div class="security-grid">${[['Node / RocketRide runtime',s.npm],['Python / gateway',s.python]].map(([name,r])=>`<section class="scan"><div class="scan-label">${name}</div><h2>${r.dependencies}</h2><p>dependencies scanned</p>${badge(r.ok?'No vulnerable paths':'Issues found',r.ok?'green':'amber')}<div class="row" style="margin-top:16px"><span class="muted">Reported issues</span><b>${r.issues}</b></div></section>`).join('')}</div>`+
 `<div class="grid" style="margin-top:23px">${panel('Remediation, not an ignore rule',`<h2>Removed the vulnerable<br>archive extraction dependency.</h2><p class="section-sub">The local RocketRide runtime omits its unused bundled CLI and uses fflate for ZIP creation. The Cloud client remains intact. Snyk’s repeat npm scan found no vulnerable paths.</p>${receipt('Resolved advisory','SNYK-JS-ADMZIP-19276676')}`)}${panel('Source-code scan',`<h2>${s.code.status==='PASSED'?'Scan completed.':s.code.status==='FINDINGS'?'Findings require review.':'Reported separately.'}</h2><p class="section-sub">${esc(s.code.reason)}</p>${badge(s.code.status==='PASSED'?'No source findings':s.code.status==='FINDINGS'?'Source findings':'Not a clean source-scan claim',s.code.status==='PASSED'?'green':'amber')}${insight('What this demo does not claim','No production warehouse deployment, regulatory certification, global containment, or measured performance improvement.')}`)}</div>`;}
const renderers={overview,signal,memory,investigate,protect,reuse,security};
function render(){
 const key=location.hash.slice(1)||'overview';
 const current=renderers[key]?key:'overview';
 const index=chapters.findIndex(c=>c[0]===current);
 document.querySelector('#chapters').innerHTML=chapters.map(([id,label],i)=>`<a href="#${id}" ${id===current?'class="active" aria-current="page"':''}><span class="nav-number">${i===0?'◈':String(i).padStart(2,'0')}</span>${label}</a>`).join('');
 const next=chapters[index+1];
 document.querySelector('#content').innerHTML=renderers[current]()+`<div class="next-chapter"><div><span>RECORDED REPLAY &nbsp; · &nbsp; ${index+1} OF ${chapters.length}</span><div class="story-progress">${chapters.map((_,i)=>`<i class="${i<=index?'seen':''}"></i>`).join('')}</div></div>${next?`<a class="next-button" href="#${next[0]}"><span>Next step<small>${next[1]}</small></span><b>→</b></a>`:'<a class="next-button" href="#overview"><span>Replay the story<small>Back to overview</small></span><b>↗</b></a>'}</div>`;
 // Presentation timing only: all facts are already loaded from recorded runs.
 document.querySelectorAll('#content .hero,#content .title-row,#content .panel,#content .stat,#content .scan').forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--delay',Math.min(i*55,330)+'ms');});
 document.querySelectorAll('#content .sponsor,#content .lot,#content .event,#content .branch .step').forEach((el,i)=>{el.classList.add('evidence-reveal');el.style.setProperty('--delay',Math.min(i*130+130,700)+'ms');});
 window.scrollTo(0,0);
 document.title=`${chapters[index][1]} · Recall Firewall`;
}
window.addEventListener('hashchange',render);
window.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,summary'))return;const current=chapters.findIndex(c=>c[0]===(location.hash.slice(1)||'overview'));const offset=e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0;if(offset){e.preventDefault();location.hash=chapters[Math.max(0,Math.min(chapters.length-1,current+offset))][0];}});
render();
